spring:
  application:
    name: config-client
  cloud:
    zookeeper:
      enabled: false # Zookeeper 服务发现与注册失效（默认）
    consul:
      enabled: false # Consul 服务发现与注册失效（默认）


server:
  port: 8083 #随机端口

## 默认 profile 关闭自动特性
eureka:
  client:
    enabled: false # Eureka 服务发现与注册失效（默认）

--- # Profile For Eureka
spring:
  profiles: eureka
# Eureka 客户端配置
eureka:
  server: # 官方不存在的配置（自定义配置）
    host: 127.0.0.1
    port: 12345
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
    registryFetchIntervalSeconds: 5 # 5 秒轮训一次
  instance:
    instanceId: ${spring.application.name}:${server.port}

--- # Profile For Zookeeper
spring:
  profiles: zookeeper
  cloud:
    zookeeper:
      enabled: true
      connectString: ecs.ali.com:2181

--- # Profile For Consul
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      host: ecs.tx.com
