spring:
  application:
    name: service-provider

  kafka:
    bootstrap-servers: ecs.ali.com:9092
    producer:
      client-id: kafka-cloud-stream
      value-serializer: com.gupaoedu.service.server.kafka.ObjectSerializer

eureka:
  server: # 官方不存在的配置（自定义配置）
    host: 127.0.0.1
    port: 12345
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
    registryFetchIntervalSeconds: 5 # 5 秒轮训一次
  instance:
    instanceId: ${spring.application.name}:${server.port}



server:
  port: 9090 #随机端口
